"""Added user_id field

Revision ID: 98c796c9deda
Revises: 85b016cc04fe
Create Date: 2025-08-03 16:06:52.720867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c796c9deda'
down_revision: Union[str, Sequence[str], None] = '85b016cc04fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_leads_full_name'), table_name='leads')
    op.create_index(op.f('ix_leads_user_id'), 'leads', ['user_id'], unique=False)
    op.drop_column('leads', 'contact_phone')
    op.drop_column('leads', 'contact_email')
    op.drop_column('leads', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('contact_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_leads_user_id'), table_name='leads')
    op.create_index(op.f('ix_leads_full_name'), 'leads', ['full_name'], unique=False)
    op.drop_column('leads', 'user_id')
    # ### end Alembic commands ###
