apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\!Software\K8s\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: auth-db
  name: auth-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: auth-db
