apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\!Software\K8s\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: D:\!Software\K8s\kompose.exe convert -f ..\docker-compose.yml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: auth
    spec:
      containers:
        - env:
            - name: ADMIN_LOGIN
              value: admin
            - name: ADMIN_PASSWORD
              value: admin1234
            - name: DB_HOST
              value: auth-db
            - name: DB_NAME
              value: dentistAuth
            - name: DB_PASSWORD
              value: x2ketarol
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PASSWORD
              value: default
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: default
          image: dentist-crm-api-auth:latest
          imagePullPolicy: IfNotPresent
          name: auth
          ports:
            - containerPort: 8001
              protocol: TCP
      restartPolicy: Always
