apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\!Software\K8s\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: bot
  name: bot
spec:
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8004
  selector:
    io.kompose.service: bot
