apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\!Software\K8s\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: users
  name: users
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8003
  selector:
    io.kompose.service: users
